// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI7DdwjfNYsjsSgebsrMkU86kcr5morGc',
    appId: '1:40362666707:web:722d63e39fa4e129514226',
    messagingSenderId: '40362666707',
    projectId: 'fir-tutorial-f803c',
    authDomain: 'fir-tutorial-f803c.firebaseapp.com',
    storageBucket: 'fir-tutorial-f803c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmDaFzimQkgmpGU2wdIo1PE-MFWeqaJgU',
    appId: '1:40362666707:android:c62b4e273234dea6514226',
    messagingSenderId: '40362666707',
    projectId: 'fir-tutorial-f803c',
    storageBucket: 'fir-tutorial-f803c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm1IISFiGQicmHiA_WAfiOsgOiFNryqC8',
    appId: '1:40362666707:ios:75bb058e153a24c5514226',
    messagingSenderId: '40362666707',
    projectId: 'fir-tutorial-f803c',
    storageBucket: 'fir-tutorial-f803c.appspot.com',
    iosBundleId: 'com.example.foodsflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm1IISFiGQicmHiA_WAfiOsgOiFNryqC8',
    appId: '1:40362666707:ios:8fe4884051df789f514226',
    messagingSenderId: '40362666707',
    projectId: 'fir-tutorial-f803c',
    storageBucket: 'fir-tutorial-f803c.appspot.com',
    iosBundleId: 'com.example.foodsflutter.RunnerTests',
  );
}
